### ISSUE TITLE
fragment syntax != QCSchema

### ISSUE THREAD

**Issue by loriab** [psi-rking/optking#25]
The fragments field of Mol you're taking in are psi-style `[[0, 3][3, 6]]` or thereabouts for water dimer. Needs to be explicit atoms (qcschema v1 https://molssi-qc-schema.readthedocs.io/en/latest/auto_topology.html) or fragment_separators : list of int
        (nfr - 1, ) list of atom indices at which to split `geom` into fragments.

**Comment by psi-rking** [comment]
@loriab , can you show where this needs to change?  Internally to optking, the fragments are incomplete (compared to qcschema) but in terms of the user-interface or external keywords, etc., where do you see a problem?  Just trying to pin this down and make sure it still applies.  For our molsys, its from_psi4_molecule() uses mol.extract_subsets()  its from_json_molecule() reads the fragments from an array.

**Comment by loriab** [comment]
you can run `get_fragment` on a qcschema mol https://github.com/MolSSI/QCElemental/blob/master/qcelemental/models/molecule.py#L535-L558, if that's handy.

what varieties of Mol can your molecular systems enter optking as (e.g., `psi4.core.Molecule`, `qcdb.Molecule`, `qcel.models.Molecule`, qcschema dictionary (what qcel.models.Mol turns into if you `dict()` or `json()` it), molrec dictionary (what psi4.core.Mol or qcdb.Mol turn into if you `to_dict()` them)? I'm afraid I've lost track.
