### ISSUE TITLE
Allow in-memory JSON

### ISSUE THREAD

**Issue by dgasmith** [psi-rking/optking#26]
Currently the JSON driver `run_json` expects a JSON serialized file, it would be great if this natively accepted a dictionary and then a wrapper which would optionally read a file off disk. This would be more canonical with other programs in the QCArchive ecosystem.

**Comment by loriab** [comment]
Good idea. I did the opposite, making a file-less wrapper around the file-full one, but it’d be good to be able to avoid disk entirely.

**Comment by AlexHeide** [comment]
Sounds good to me

**Comment by AlexHeide** [comment]
Apparently I did this last November and forgot to close this. 

Slight renaming will occur in future pull request from my fork to `run_qcschema` and `run_json_file` from `run_json_dict` and `run_json`

**Comment by dgasmith** [comment]
Great! Is this ready to hook up to QCEngine?

**Comment by psi-rking** [comment]
I think it is, and psi4 too - at least as far as the optimizer functionality goes.  I just haven't gotten around to investigating these next steps.

**Comment by loriab** [comment]
Great! I think optking+qcengine first by duplicating the geomeTRIC tests and making sure optking can run them will nail down and translations between summer2018 json and qcschema json. Then [psi4-ddd](https://github.com/psi4/psi4/pull/1351)+qcengine will add both optimizers to psi and we can skip psi4/psi4#1335

**Comment by AlexHeide** [comment]
Still need to adjust our qcschema class to match the official optimizer format. I will hopefully have that done this week. I have a few bug fixes on my fork to merge. That should be it AFAIK.

**Comment by loriab** [comment]
once upon a time, I added some return info to geometric (unofficially) https://github.com/loriab/geomeTRIC/commit/b9b0a9e2f008417c2ebffb5ee67de542de3851f3#diff-2af7dd72b77dac63cea64c052a549fe0R1043-R1049 . may lobby to get that back. but that's more of a schema discussion than an optking one.

**Comment by psi-rking** [comment]
You wanted to return the convergence criteria?  Of all things, that seems
strange.
BTW, we do have the optimization trajectory (or IRC path) in the json
output.

**Comment by dgasmith** [comment]
You can consider grabbing the QCSchema objects directly from QCElemental: https://github.com/MolSSI/QCElemental/blob/master/qcelemental/models/procedures.py#L24

As a note, we do not yet have an "official" geometry optimization schema yet.

**Comment by loriab** [comment]
The current state of the opt and what the optimizer program thinks the criteria are, yes. Though it seems strange to you and me, you can't set these in geometric or otherwise know their values.

No IRC yet https://github.com/MolSSI/QCElemental/blob/master/qcelemental/models/procedures.py#L40 . An IRC would probably be a different class derived from `ProtoModel`. Then could use `trajectory` like for ordinary opt.
