### ISSUE TITLE
Hessian Guess / CodeCov decrease

### ISSUE THREAD

**Issue by AlexHeide** [psi-rking/optking#42]
A few commits ago, we removed the keyword controlling selection of hessian guessing.
From what I can tell, this is (largely) why the code coverage has decreased and we couldn't see it due to some Travis issues. 

Fix incoming later today

**Comment by psi-rking** [comment]
We did?  There is still "intrafrag_hess" keyword with 6 options.  Do you mean we removed the test the uses them all?

**Comment by AlexHeide** [comment]
`H = hessian.guess(oMolsys, op.Params.intrafrag_hess)` is what's currently in optimize
The method signature is `def guess(oMolsys, connectivity=None, guessType="SIMPLE"):` 
The real issue is that we never got rid of the connectivity parameter

**Comment by psi-rking** [comment]
OK.  Looks like you can just delete the connectivity parameter which is being overridden anyway now.  Relic from switching to passing the Molsys.
