### ISSUE TITLE
Hessian Updating

### ISSUE THREAD

**Issue by AlexHeide** [psi-rking/optking#75]
This difference between optimizers was noted in psi4/psi4#2727

cpp_optking used the very first step to update the Hessian and uses the most recent step to update the hessian.

Currently optking ignores the most recent step and therefore in the second step does not update the hessian. This behavior should be tested.

The relevant lines of code at least the ones I know of.

The initial quit if there are fewer than 2 steps.
https://github.com/psi-rking/optking/blob/765fe078615b89deb1e35e0dc0d6e7b70508b66a/optking/history.py#L245

Initialization of the iteration variable over the steps to update with.
https://github.com/psi-rking/optking/blob/765fe078615b89deb1e35e0dc0d6e7b70508b66a/optking/history.py#L278-L279

I believe there is another piece of logic active, the first hessian update skips the first step without these two pieces of logic.

**Comment by AlexHeide** [comment]
@psi-rking Pinging since you asked for the relevant pieces of code in the psi4 discussion.

**Comment by psi-rking** [comment]
I am looking at it.  See what you mean.  "Updating Hessian ..." is called on 2nd step, but it doesn't actually change the Hessian.  There used to be a partial step added to the array with incomplete data, and I wonder now if the elimination of that has changed this intended behavior.

**Comment by psi-rking** [comment]
OK!  Looking at the code and jogging my memory.  I do think that this behavior has come in accidentally.  I see that len(steps) when hessian_update() is called for the 2nd time is now 1.  This make sense, there is one past step.  However, this used to be 2 with the current step also taking a spot.  It's definitely worth trying to change.

**Comment by psi-rking** [comment]
Would you like me to make the pull request or would you like to do it?

**Comment by psi-rking** [comment]
Hmmm.  The hessian_update() was written presuming that the current step forces are included in the final slot in steps.  This is apparently not true anymore.  So may not be trivial change.

**Comment by psi-rking** [comment]
In other words, we used to do things in this order:
cartesian gradient -> transform to internal forces -> update hessian
now the order of things appears to be:
update hessian -> compute gradient -> transform the forces

**Comment by AlexHeide** [comment]
I have modified the code to update the hessian with the most recent step. Few of the tests finish in the same number of iterations as before. Most are finishing +-1 step with a few at +- 3 steps. There isn't a clear winner so far. I'll likely need to run the baker test set before making a judgement as to which is better in terms of optimization process.

**Comment by psi-rking** [comment]
Probably worth trying but that Baker test set can be misleading.  They are
all (or almost all) rigid structures with easily guessed Hessians.  In
fact, calculating the initial hessian for that test set doesn't help much,
as I recall.  - So may be misleading in regards to the optimal general
algorithm.  Still, one has to go by something.
