### ISSUE TITLE
NEW FEATURE: add line search step algorithm

### ISSUE THREAD

**Issue by psi-rking** [psi-rking/optking#8]
typically inefficient but good for very difficult cases.  Perhaps useful for constrained optimizations where only a small number of floppy degrees of freedom are in focus.

**Comment by psi-rking** [comment]
@AlexHeide , maybe we can close this one?

**Comment by AlexHeide** [comment]
Linesearching first appeared in 339bc58c2d7c0397012d6b956984cdb58cd9badf
I will close
