### ISSUE TITLE
g_convergence interfrag_tight

### ISSUE THREAD

**Issue by loriab** [psi-rking/optking#81]
Did the `interfrag_tight` convergence crit set get deliberately discarded or lost in transition? Which would be simpler to update -- add it back here or delete it in p4? https://psicode.org/psi4manual/master/optking.html?highlight=interfrag_tight#id25

Apologies if I ought to have found the answer by searching my memory or GH.

**Comment by psi-rking** [comment]
I'm going to punt to @AlexHeide on this one, because he rewrote the convergence check into something quite abstract.  It could have been dropped at this point not long ago, but it's also possible it had already been lost.

**Comment by psi-rking** [comment]
I don't have a strong opinion on option availability.  But
distance-displacement criteria for interfragment motions can be almost
impossible to converge to our typical intrafragment limits.

**Comment by lukekurfman** [comment]
Having the option to change the criteria between the cluster and its fragments could be useful, if it's not too tiresome to implement.

**Comment by loriab** [comment]
And sorry for the slow response, btw. I neglected to check back or tell Luke that this was open. If you've already gone with an implementation, that's fine, too.
